MODE: human_classifier

F_keys: ['dense']
L_keys: ['labels_s']
DATA_DIR: ['data/hico']

TRAIN:
  DATASET:
    BATCH_SIZE: [48]
    NUM_WORKERS: 4
    SAMPLER_NAME: "priority_object"
    JITTERING: True
  MAX_EPOCH: 100
  OPTIMIZER:
    TYPE: SGD
    RESUME: False
    lr: 7e-3
    momentum: 0.9
    weight_decay: 1e-7
    alpha: 0.99
    eps: 1e-8
    GROUP: 'ALL' # 'ALL', 'P_CLS' or 'LAST'
    KW: 'mean.fc_out.weight'
    KB: 'mean.fc_out.bias'
  
TEST:
  BATCH_SIZE: 48
  NUM_WORKERS: 4

MODEL:
  ENCODER:
    RESNET: False
    BN: True
    LAYER_SIZE: [3, 256, 512]
    KERNEL_SIZE: [0, 5, 3]
    PADDING: [0, 2, 1]
    ACT: 'ReLU'
  ACT: 'ReLU'
  KEY: ['dense', 'labels_s']
  LAYER_SIZE: [512, 256]
  NUM_CLASSES: 117
  BN: True
  UNSUP_FAC: 0
  CHECKPOINT: 
  